### ISSUE TITLE
addSelfAsDependency() fails when installing from local

### ISSUE THREAD

**Issue by passsy** [phntmxyz/sidekick#145]
```
 ./vgs sidekick plugins install -s path ~/Projects/passsy/flutterw_sidekick_plugin/
```

```
Error on line 1, column 7 of /Users/pascalwelsch/Projects/passsy/flutterw_sidekick_plugin/pubspec.yaml: "name" field doesn't match expected name "/Users/pascalwelsch/Projects/passsy/flutterw_sidekick_plugin/".
  ╷
1 │ name: flutterw_sidekick_plugin
  │       ^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
Unhandled exception:
/Users/pascalwelsch/Downloads/vgv_start/packages/vgs_sidekick/build/cache/dart-sdk/bin/dart pub add /Users/pascalwelsch/Projects/passsy/flutterw_sidekick_plugin/ --path /Users/pascalwelsch/Projects/passsy/flutterw_sidekick_plugin/ 
exit: 65
reason: The command [/Users/pascalwelsch/Downloads/vgv_start/packages/vgs_sidekick/build/cache/dart-sdk/bin/dart] with args [pub, add, /Users/pascalwelsch/Projects/passsy/flutterw_sidekick_plugin/, --path, /Users/pascalwelsch/Projects/passsy/flutterw_sidekick_plugin/] failed with exitCode: 65 workingDirectory: /Users/pascalwelsch/Downloads/vgv_start/packages/vgs_sidekick
#0      waitForEx (package:dcli/src/util/wait_for_ex.dart:67:5)
#1      RunnableProcess.processUntilExit (package:dcli/src/util/runnable_process.dart:460:7)
#2      RunnableProcess.run (package:dcli/src/util/runnable_process.dart:180:11)
#3      startFromArgs (package:dcli/src/functions/run.dart:174:19)
#4      SidekickDartRuntime.dart (package:sidekick_core/src/dart_runtime.dart:54:5)
#5      addDependency (package:sidekick_plugin_installer/src/add_dependency.dart:119:23)
#6      addSelfAsDependency (package:sidekick_plugin_installer/src/add_dependency.dart:29:5)
#7      main (file:///Users/pascalwelsch/Downloads/vgv_start/packages/vgs_sidekick/build/plugins/flutterw_sidekick_plugin/tool/install.dart:23:3)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Unhandled exception:
/Users/pascalwelsch/Downloads/vgv_start/packages/vgs_sidekick/build/cache/dart-sdk/bin/dart /Users/pascalwelsch/Downloads/vgv_start/packages/vgs_sidekick/build/plugins/flutterw_sidekick_plugin/tool/install.dart 
exit: 255
reason: The command [/Users/pascalwelsch/Downloads/vgv_start/packages/vgs_sidekick/build/cache/dart-sdk/bin/dart] with args [/Users/pascalwelsch/Downloads/vgv_start/packages/vgs_sidekick/build/plugins/flutterw_sidekick_plugin/tool/install.dart] failed with exitCode: 255 workingDirectory: /Users/pascalwelsch/Downloads/vgv_start/packages/vgs_sidekick
#0      waitForEx (package:dcli/src/util/wait_for_ex.dart:67)
#1      RunnableProcess._waitForExit (package:dcli/src/util/runnable_process.dart:331)
#2      RunnableProcess.run (package:dcli/src/util/runnable_process.dart:177)
#3      startFromArgs (package:dcli/src/functions/run.dart:174)
#4      SidekickDartRuntime.dart (package:sidekick_core/src/dart_runtime.dart:54)
#5      InstallPluginCommand.run (package:sidekick_core/src/commands/plugins/install_plugin_command.dart:189)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:209)
<asynchronous suspension>
#7      SidekickCommandRunner.run (package:sidekick_core/sidekick_core.dart:162)
<asynchronous suspension>
#8      runVgs (package:vgs_sidekick/vgs_sidekick.dart:31)
<asynchronous suspension>
#9      main (file:///Users/pascalwelsch/Downloads/vgv_start/packages/vgs_sidekick/bin/main.dart:4)
<asynchronous suspension>
```

**Comment by Giuspepe** [comment]
Will be fixed by https://github.com/phntmxyz/sidekick/pull/144 as well
