### ISSUE TITLE
`sidekick init` crashes with `sidekick 0.8.0` `sidekick_core 0.15.1`

### ISSUE THREAD

**Issue by Giuspepe** [phntmxyz/sidekick#194]
The current latest version of `sidekick` has some problems.

I assume that this is because `sidekick 0.8.0` didn't have locked dependencies yet , so its dependency on `sidekick_core: '>=0.13.0 <1.0.0'` currently resolves to `0.15.1` which it is incompatible with.

So we should probably release a new `sidekick` version with our new release command to make sure that the latest `sidekick` on pub has locked dependencies and the following errors don't occur anymore.

<details>
<summary>Running sidekick init in a fresh project & directory crashes</summary>

```
❯ sidekick init
Welcome to sidekick. You're about to initialize a sidekick project


Enter the directory in which the entrypoint script should be created.
Or press enter to use the current directory.
 [/Users/pepe/repos/samples/foo] 

Enter the directory in which the CLI package should be created.
Must be an absolute path or a path relative to the repository root (/Users/pepe/repos/samples/foo).
Or press enter to use the suggested directory.
 [/Users/pepe/repos/samples/foo/packages] 
Please select a name for your sidekick CLI.
We know, selecting a name is hard. Here are some suggestions:
  1) f
  2) sf
  3) fo
  4) spf
  5) Enter your own
Type the number of the fitting acronym or choose Enter your own 
You must enter a value.
Type the number of the fitting acronym or choose Enter your own 1

Generating f_sidekick
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint:   git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint:   git branch -m <name>
Initialized empty Git repository in /Users/pepe/repos/samples/foo/.git/
Unhandled exception:
FileSystemException: Cannot open file, path = '/Users/pepe/repos/samples/foo/packages/f_sidekick/lib/src/f_project.dart' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      FileModifier.replaceSectionWith (package:sidekick_core/src/file_util.dart:11:22)
#5      InitCommand._addPackagesToProjectClass (package:sidekick/src/init/init_command.dart:257:22)
#6      InitCommand.createSidekickPackage (package:sidekick/src/init/init_command.dart:194:5)
<asynchronous suspension>
#7      InitCommand.run (package:sidekick/src/init/init_command.dart:140:5)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      main (package:sidekick/sidekick.dart:21:5)
<asynchronous suspension>
#10     main (file:///Users/pepe/.pub-cache/hosted/pub.dartlang.org/sidekick-0.8.0/bin/sidekick.dart:4:3)
<asynchronous suspension>
❯ sidekick --version
sidekick: 0.8.0
sidekick_core: 0.15.1
```
</details>

<details>
<summary>The CLI works, but prints this:</summary>

```
Dependency sidekick_core:0.10.0 doesn't match sidekick.cli_version 0.15.1 in your pubspec.yaml.
This is a signal that sidekick_core was updated manually without calling 'sidekick update'. Some features in your CLI might not work as expected.

Please run f sidekick update to execute the missing migrations.
```

```
❯ ./f sidekick update
No need to update because you are already using the latest sidekick cli version.
```
</details>

<details>
<summary>pubspec.yaml</summary>

```
name: f_sidekick
description: Sidekick CLI for f
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

executables:
  main:

dependencies:
  sidekick_core: '>=0.10.0 <1.0.0'

dev_dependencies:
  lint: ^1.5.3

# generated code, do not edit this manually
sidekick:
  cli_version: 0.15.1
```
</details>

**Comment by Giuspepe** [comment]
The crash was fixed by releasing `sidekick 0.9.0`, but the update message still prints erroneously. This is because the sidekick CLI generated by `sidekick init` has a dependency `sidekick_core: '>=0.10.0 <1.0.0'` and the lower version `0.10.0` doesn't match with `sidekick: cli_version: 0.15.1` which triggers the following message

```
Dependency sidekick_core:0.10.0 doesn't match sidekick.cli_version 0.15.1 in your pubspec.yaml.
This is a signal that sidekick_core was updated manually without calling 'sidekick update'. Some features in your CLI might not work as expected.

Please run f sidekick update to execute the missing migrations.
```
