### ISSUE TITLE
FormatCommand verify does not print a clear error message

### ISSUE THREAD

**Issue by Giuspepe** [phntmxyz/sidekick#222]
Found this running on CI:

```
Run ./<sidekick-cli> format --verify
Verifying package:foo
Formatted 7 files (0 changed) in 0.32 seconds.
Verifying package:bar
Changed /__w/bar/.../x.dart
Changed /__w/bar/.../y.dart
Formatted 17 files (2 changed) in 0.46 seconds.
Unhandled exception:
Instance of 'DartFileFormatException'
#0      FormatCommand._verifyThrow (package:sidekick_core/src/commands/format_command.dart:132)
#1      FormatCommand.run (package:sidekick_core/src/commands/format_command.dart:126)
#2      CommandRunner.runCommand (package:args/command_runner.dart:212)
#3      SidekickCommandRunner.run (package:sidekick_core/sidekick_core.dart:291)
Error: Process completed with exit code 255.
```

We should print a clear error message like `Dart files are not correctly formatted. Run "${SidekickContext.cliName} format" to format the code.` (in red)

**Comment by Giuspepe** [comment]
Also: We print `Changed /__w/bar/.../x.dart` and `Formatted 17 files (2 changed) in 0.46 seconds.`, although no files are ever changed because when `verify = true` we pass `--output=none`
